In [1]:
import pandas as pd
import scipy 
import numpy as np
from scipy import stats

In [2]:
sales=pd.read_csv("C:\\Users\\Admin\\Documents\\Hypothesis testing assignment\\BuyerRatio.csv")

In [3]:
sales

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [20]:
sales.drop("Observed Values", axis=1, inplace=True)

In [4]:
#h0 = Proporations are equal
#h1 = Proportions are different

In [21]:
sales

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [22]:
table = [[50,142,131,70],
        [435,1523,1356,750]]

In [23]:
stat, p, dof, exp = stats.chi2_contingency(sales)
print(stat,"\n", p,"\n", dof,"\n", exp)

1.595945538661058 
 0.6603094907091882 
 3 
 [[  42.76531299  146.81287862  131.11756787   72.30424052]
 [ 442.23468701 1518.18712138 1355.88243213  747.69575948]]


In [10]:
stats.chi2_contingency(table)

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [24]:
O = np.array([50, 142, 131, 70, 435, 1523, 1356, 750])
E = np.array([42.76531299,  146.81287862,  131.11756787, 72.30424052, 442.23468701, 1518.18712138, 1355.88243213, 747.69575948])

In [25]:
statistics, p_value = stats.chisquare(O, E, ddof = 3)
print("Statistics = ",statistics,"\n",'P_Value = ', p_value)

Statistics =  1.5959455390914483 
 P_Value =  0.8095206646905712


In [ ]:
# Not enough evidence to reject the null hypothesis